env:
  - GO111MODULE=on
  
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: 386
    main: ./gm.go
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
     - -s -w -X 'main.gmVersion={{.Version}}' -X 'main.gmBuildCommit={{.Commit}}' -X 'main.gmBuildTimestamp={{.Date}}'

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip

checksum:
  name_template: "checksums.txt"
  algorithm: sha512

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch

signs:
  - artifacts: all
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}",  "--detach-sign",  "${artifact}"]

milestones:
  - close: true
    name_template: "{{ .Version }}"

snapcrafts:
  - name: gum
    grade: stable
    confinement: classic
    license: Apache-2.0
    publish: true
    summary: "Gum is a Gradle/Maven/Ant/Bach/JBang wrapper written in Go"
    description: |
      Gum is a Gradle/Maven/Ant/Bach/JBang wrapper written in Go, inspired in https://github.com/dougborg/gdub and https://github.com/srs/gw.
      Gum automatically detects if the project is Gradle, Maven, Ant, Bach, or JBang based and runs the appropriate command. However 
      in the case that Gum guesses wrong you can force a specific build tool to be used. Similarly as gdub, Gum lets you invoke either 
      Gradle, Maven, or Ant from anywhere within the project structure, not just the root directory.

      **Usage**

      Gum supports the following flags

      * **-ga** force Ant execution
      * **-gb** force Bach execution
      * **-gc** displays current configuration and quits
      * **-gd** displays debug information
      * **-gg** force Gradle build
      * **-gh** displays help information
      * **-gj** force JBang execution
      * **-gm** force Maven build
      * **-gn** executes nearest build file
      * **-gq** run gm in quiet mode
      * **-gr** do not replace goals/tasks
      * **-gv** displays version information

      Gum will execute the build based on the root build file unless **-gn** is specified, in which case the nearest build file
      will be selected. If a specific build file is given (**-b**, **--build-file** for Gradle; **-f**, **--file** for Maven,
      **-f**, **-file**, **-buildfile** for Ant) then that file will be used instead.

brews:
  - name: gum
    goarm: 6
    repository:
      owner: kordamp
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/kordamp/gm"
    description: "Gum is a Gradle/Maven/Ant/Bach/JBang wrapper written in Go"
    license: Apache-2.0
    skip_upload: auto

chocolateys:
  - name: gm
    owners: Kordamp
    title: Gum
    authors: Andres Almiray
    project_url: https://github.com/kordamp/gm
    # App's icon.
    icon_url: 'https://rawcdn.githack.com/foo/bar/efbdc760-395b-43f1-bf69-ba25c374d473/icon.png'
    copyright: 2020 Andres Almiray
    license_url: https://github.com/kordamp/gm/blob/master/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/kordamp/gm
    docs_url: https://github.com/kordamp/gm/blob/main/README.adoc
    bug_tracker_url: https://github.com/kordamp/gm/issues
    tags: "maven gradle jbang ant bach wrapper java"
    summary: "Gum is a Gradle/Maven/Ant/Bach/JBang wrapper written in Go"
    description: |
      Gum is a Gradle/Maven/Ant/Bach/JBang wrapper written in Go, inspired in https://github.com/dougborg/gdub and https://github.com/srs/gw.
      Gum automatically detects if the project is Gradle, Maven, Ant, Bach, or JBang based and runs the appropriate command. However 
      in the case that Gum guesses wrong you can force a specific build tool to be used. Similarly as gdub, Gum lets you invoke either 
      Gradle, Maven, or Ant from anywhere within the project structure, not just the root directory.

      **Usage**

      Gum supports the following flags

      * **-ga** force Ant execution
      * **-gb** force Bach execution
      * **-gc** displays current configuration and quits
      * **-gd** displays debug information
      * **-gg** force Gradle build
      * **-gh** displays help information
      * **-gj** force JBang execution
      * **-gm** force Maven build
      * **-gn** executes nearest build file
      * **-gq** run gm in quiet mode
      * **-gr** do not replace goals/tasks
      * **-gv** displays version information

      Gum will execute the build based on the root build file unless **-gn** is specified, in which case the nearest build file
      will be selected. If a specific build file is given (**-b**, **--build-file** for Gradle; **-f**, **--file** for Maven,
      **-f**, **-file**, **-buildfile** for Ant) then that file will be used instead.
    release_notes: "https://github.com/kordamp/gm/releases/tag/v{{ .Version }}"
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
    source_repo: "https://push.chocolatey.org/"

announce:
  skip: '{{ .IsSnapshot }}'
  twitter:
    enabled: true
    message_template: '🚀 {{ .ProjectName }} {{ .Tag }} has been released! {{ .ReleaseURL }}'
  mastodon:
    enabled: true
    message_template: '🚀 {{ .ProjectName }} {{ .Tag }} has been released! {{ .ReleaseURL }}'
    server: https://mastodon.social
